Repository pondokcoder2020/PDC00001, pull requests merged in 2020-07, with the labels that each got.

#21 Master Poli
  api/app/Poli.php
  api/app/Tindakan.php
  client/pages/master/poli/poli/index.php
  client/pages/master/poli/poli/tambah.php
  client/pages/master/poli/tindakan/index.php
  client/script/master/poli/poli/index.php
  client/script/master/poli/poli/tambah.php
  client/script/master/poli/tindakan/index.php
Labels: new feature

#28 Query manager
  api/app/Query.php
Labels: Fix, enhancement

#33 Fix edit jabatan pada pegawai
  api/app/Pegawai.php
  client/pages/pegawai/edit.php
  client/pages/pegawai/tambah.php
  client/script/pegawai/index.php
  client/script/pegawai/tambah.php
Labels: new feature

#34 Data master
  api/app/Terminologi.php
  client/pages/terminologi/child.php
  client/pages/terminologi/edit.php
  client/pages/terminologi/index.php
  client/pages/terminologi/tambah.php
  client/script/terminologi/child.php
  client/script/terminologi/edit.php
  client/script/terminologi/index.php
  client/script/terminologi/tambah.php
Labels: enhancement

#35 Pegawai
  api/app/Terminologi.php
  client/pages/terminologi/child.php
  client/pages/terminologi/edit.php
  client/pages/terminologi/index.php
  client/pages/terminologi/tambah.php
  client/script/terminologi/child.php
  client/script/terminologi/edit.php
  client/script/terminologi/index.php
  client/script/terminologi/tambah.php
Labels: enhancement

#36 Data Pasien
  api/app/Pasien.php
  client/pages/pasien/index.php
  client/pages/pasien/tambah.php
  client/script/pasien/index.php
  client/script/pasien/tambah.php
Labels: new feature

#37 Sync Design
  api/app/Pegawai.php
  api/app/Upload.php
  client/head.php
  client/header.php
  client/pages/igd/asesmen-awal-1.php
  client/pages/igd/asesmen-awal-2.php
  client/pages/igd/asesmen-keperawatan-1.php
  client/pages/igd/asesmen-keperawatan-2.php
  client/pages/igd/asesmen-keperawatan-3.php
  client/pages/igd/asesmen-keperawatan-4.php
  client/pages/igd/asesmen-keperawatan.php
  client/pages/igd/index.php
  client/pages/igd/info-pasien.php
  client/pages/igd/tambah.php
  client/pages/pegawai/edit.php
  client/pages/pegawai/jabatan/index.php
  client/pages/pegawai/tambah.php
  client/script.php
  client/script/igd/asesmen-keperawatan.php
  client/script/igd/index.php
  client/script/igd/tambah.php
  client/script/pegawai/edit.php
  client/script/pegawai/index.php
  client/script/pegawai/jabatan/index.php
  client/script/pegawai/tambah.php
Labels: enhancement

#38 Data master
  api/app/Pasien.php
  api/app/Terminologi.php
  api/app/Wilayah.php
  client/pages/pasien/index.php
  client/pages/pasien/tambah.php
  client/pages/terminologi/child.php
  client/pages/terminologi/edit.php
  client/pages/terminologi/index.php
  client/pages/terminologi/tambah.php
  client/script/pasien/index.php
  client/script/pasien/tambah.php
  client/script/terminologi/child.php
  client/script/terminologi/edit.php
  client/script/terminologi/index.php
  client/script/terminologi/tambah.php
Labels: enhancement

#43 Inventori
  api/app/PO.php
  api/app/Poli.php
  api/app/Query.php
  client/builder.php
  client/pages/inventori/po/form-po-lampiran.php
  client/pages/inventori/po/form-po-utama.php
  client/pages/inventori/po/index.php
  client/pages/inventori/po/tambah.php
  client/pages/master/poli/poli/edit.php
  client/pages/pegawai/edit.php
  client/pages/rawat_jalan/resepsionis/index.php
  client/script.php
  client/script/inventori/po/tambah.php
  client/script/master/poli/poli/edit.php
  client/script/rawat_jalan/resepsionis/index.php
Labels: enhancement

#47 Fix default password new pegawai 123456
  api/app/Pegawai.php
Labels: Fix, enhancement

#50 Rawat jalan Feature Updated
  api/app/Antrian.php
  api/app/Pegawai.php
  api/app/Penjamin.php
  api/app/Poli.php
  api/app/Tindakan.php
  client/pages/antrian_resepsionis/index.php
  client/pages/antrian_resepsionis/tambah.php
  client/pages/rawat_jalan/dokter/action-panel.php
  client/pages/rawat_jalan/dokter/antrian.php
  client/pages/rawat_jalan/dokter/asesmen-awal.php
  client/pages/rawat_jalan/dokter/asesmen-rawat.php
  client/pages/rawat_jalan/dokter/index.php
  client/pages/rawat_jalan/dokter/resep.php
  client/pages/rawat_jalan/dokter/review.php
  client/pages/rawat_jalan/dokter/tindakan.php
  client/script/antrian_resepsionis/index.php
  client/script/antrian_resepsionis/tambah.php
  client/script/rawat_jalan/dokter/antrian.php
  client/script/rawat_jalan/dokter/index.php
Labels: enhancement, new feature

#64 Fix update query segment. NULL Management Fix
  api/app/Query.php
Labels: Fix, bug

#69 Rawat jalan
  api/app/Antrian.php
  api/app/Asesmen.php
  api/app/Penjamin.php
  api/app/Poli.php
  api/app/Query.php
  client/pages/rawat_jalan/dokter/antrian.php
  client/pages/rawat_jalan/dokter/asesmen-awal.php
  client/pages/rawat_jalan/dokter/cppt.php
  client/pages/rawat_jalan/dokter/resep.php
  client/pages/rawat_jalan/dokter/review.php
  client/script/rawat_jalan/dokter/antrian.php
Labels: Fix, enhancement, new feature

#85 PO Fixed document manager
  .gitignore
  api/app/PO.php
  api/app/Query.php
  api/app/Supplier.php
  client/pages/apotek/resep/index.php
  client/pages/inventori/po/form-po-utama.php
  client/pages/inventori/po/index.php
  client/pages/inventori/po/tambah.php
  client/script/apotek/resep/index.php
  client/script/inventori/po/index.php
  client/script/inventori/po/tambah.php
  client/script/rawat_jalan/dokter/antrian.php
Labels: Fix, enhancement

#86 PO DO conflict PO class
  .gitignore
  api/app/Asesmen.php
  api/app/Inventori.php
  api/app/PO.php
  api/app/Query.php
  api/app/Supplier.php
  client/builder.php
  client/pages/apotek/resep/index.php
  client/pages/inventori/po/form-po-utama.php
  client/pages/inventori/po/index.php
  client/pages/inventori/po/tambah.php
  client/pages/rawat_jalan/dokter/resep.php
  client/pages/rawat_jalan/dokter/tindakan.php
  client/script.php
  client/script/apotek/resep/index.php
  client/script/inventori/po/index.php
  client/script/inventori/po/tambah.php
  client/script/rawat_jalan/dokter/antrian.php
  client/script/rawat_jalan/dokter/index.php
Labels: bug, enhancement

#98 Fixing Asesmen Rawat
  api/app/Antrian.php
  api/app/Asesmen.php
  api/app/AssesmenRawatJalan.php
  api/app/Poli.php
  client/pages/rawat_jalan/perawat/antrian.php
  client/pages/rawat_jalan/perawat/index.php
  client/pages/rawat_jalan/resepsionis/tambah.php
  client/script/rawat_jalan/perawat/antrian.php
  client/script/rawat_jalan/perawat/index.php
  client/script/rawat_jalan/resepsionis/tambah.php
Labels: Fix

#100 Kasir menggunakan fitur Sync
  .gitignore
  api/app/Anjungan.php
  api/app/Notification.php
  api/app/Pegawai.php
  api/app/Query.php
  client/builder.php
  client/header.php
  client/pages/display/index.php
  client/pages/rawat_jalan/resepsionis/index.php
  client/pages/setting/socket/index.php
  client/script/anjungan/index.php
  client/script/display/index.php
  client/script/rawat_jalan/resepsionis/index.php
  client/script/setting/socket/index.php
  client/script/setting/socket/new_page.php
  sync.php
Labels: enhancement

#102 Stand by Fitur Sync pada bagian PO
  .gitignore
  api/app/Anjungan.php
  api/app/Antrian.php
  api/app/Apotek.php
  api/app/Asesmen.php
  api/app/AssesmenRawatJalan.php
  api/app/DeliveryOrder.php
  api/app/Inventori.php
  api/app/Notification.php
  api/app/PO.php
  api/app/Pasien.php
  api/app/Pegawai.php
  api/app/Poli.php
  api/app/Query.php
  client/builder.php
  client/header.php
  client/pages/apotek/resep/index.php
  client/pages/display/index.php
  client/pages/inventori/batch/index.php
  client/pages/inventori/do/index.php
  client/pages/inventori/do/tambah.php
  client/pages/inventori/po/detail.php
  client/pages/inventori/po/view-po-lampiran.php
  client/pages/inventori/po/view-po-utama.php
  client/pages/rawat_jalan/dokter/antrian.php
  client/pages/rawat_jalan/dokter/perawat/form.php
  client/pages/rawat_jalan/dokter/perawat/halaman1.php
  client/pages/rawat_jalan/dokter/perawat/halaman2.php
  client/pages/rawat_jalan/perawat/antrian.php
  client/pages/rawat_jalan/perawat/halaman1.php
  client/pages/rawat_jalan/perawat/halaman2.php
  client/pages/rawat_jalan/perawat/index.php
  client/pages/rawat_jalan/resepsionis/index.php
  client/pages/rawat_jalan/resepsionis/tambah.php
  client/pages/setting/socket/index.php
  client/script/anjungan/index.php
  client/script/apotek/resep/index.php
  client/script/display/index.php
  client/script/inventori/do/index.php
  client/script/inventori/do/tambah.php
  client/script/inventori/po/detail.php
  client/script/inventori/po/index.php
  client/script/master/inventori/gudang/index.php
  client/script/rawat_jalan/dokter/antrian.php
  client/script/rawat_jalan/perawat/antrian.php
  client/script/rawat_jalan/perawat/index.php
  client/script/rawat_jalan/resepsionis/index.php
  client/script/rawat_jalan/resepsionis/tambah.php
  client/script/setting/socket/index.php
  client/script/setting/socket/new_page.php
  client/script/sync/app.js
  document/po/PO_07_0001-1.pdf
  images/produk/b2078f65-b2dd-43fc-8b76-983710a6f64f.png
  sync.php
Labels: enhancement
