Repository pondokcoder2020/PDC00001, pull requests merged in 2020-08, with the labels that each got.

#108 coba test
  testhtmllabor.php
Labels: new feature

#111 Radiologi merge to master
  api/app/Antrian.php
  api/app/Pasien.php
  api/app/Radiologi.php
  client/pages/radiologi/antrian.php
  client/pages/radiologi/gambar.php
  client/pages/radiologi/hasil.php
  client/pages/radiologi/index.php
  client/script/radiologi/antrian.php
  client/script/radiologi/index.php
Labels: enhancement

#112 1. Fixing datatable for radiologi queue
  client/script/radiologi/index.php
Labels: Fix

#113 Merge for using master branch function and api for lab branch
  api/app/Antrian.php
  api/app/Pasien.php
  api/app/Radiologi.php
  client/pages/radiologi/antrian.php
  client/pages/radiologi/gambar.php
  client/pages/radiologi/hasil.php
  client/pages/radiologi/index.php
  client/script/radiologi/antrian.php
  client/script/radiologi/index.php
Labels: enhancement

#114 Fixing api for Radiologi
  api/app/Radiologi.php
Labels: Fix

#115 Bugs double upload document lampiran Radiologi
  client/script/radiologi/antrian.php
Labels: Fix

#117 Fix Error DO pada issue
  client/script/apotek/resep/index.php
  client/script/inventori/do/tambah.php
Labels: Fix

#120 Split module for tindakan rawat jalan dan rawat inap
  api/app/Tindakan.php
  client/pages/master/tindakan/rawat_inap/index.php
  client/pages/master/tindakan/rawat_jalan/index.php
  client/script/master/poli/edit.php
  client/script/master/poli/tambah.php
  client/script/master/tindakan/rawat_inap/index.php
  client/script/master/tindakan/rawat_jalan/index.php
Labels: enhancement
